package com.slangdictionary.service;

import com.slangdictionary.model.SlangDictionary;
import com.slangdictionary.model.SlangWord;
import java.io.*;
import java.nio.file.*;
import java.util.*;

public class FileService {

    public SlangDictionary loadSlangDictionary(String filePath) throws IOException {
        SlangDictionary dictionary = new SlangDictionary();

        try {

            List<String> allLines = Files.readAllLines(Paths.get(filePath));
            List<String> lines = allLines.subList(1, allLines.size());

            int lineCount = 0;
            int successCount = 0;
            int autoGeneratedCount = 0;

            for (String line : lines) {
                lineCount++;
                line = line.trim();
                if (line.isEmpty()) continue;

                boolean processed = false;

                try {
                    if (line.contains("`")) {
                        String[] parts = line.split("`", 2);
                        if (parts.length == 2) {
                            String slangWord = parts[0].trim();
                            String definitions = parts[1].trim();

                            if (!slangWord.isEmpty() && !definitions.isEmpty()) {
                                // Xử lý trường hợp có nhiều definition phân cách bằng |
                                String[] definitionList = definitions.split("\\|");

                                for (String definition : definitionList) {
                                    definition = definition.trim();
                                    if (!definition.isEmpty()) {
                                        dictionary.addSlang(slangWord, definition);
                                        successCount++;
                                    }
                                }
                                processed = true;
                            }
                        }
                    }

                    // Nếu không match format nào, tạo slang word rỗng và dùng cả dòng làm definition
                    if (!processed) {
                        // Tạo slang word rỗng (có thể dùng empty string hoặc generate ID)
                        String autoSlangWord = generateSlangWordFromDefinition(line);
                        dictionary.addSlang(autoSlangWord, line);
                        autoGeneratedCount++;
                        System.out.println("🔧 Auto-generated for line " + lineCount + ": [" + autoSlangWord + "] -> " +
                                (line.length() > 50 ? line.substring(0, 50) + "..." : line));
                    }

                } catch (Exception e) {
                    // Nếu có lỗi trong xử lý, vẫn tạo entry với slang word rỗng
                    String autoSlangWord = generateSlangWordFromDefinition(line);
                    dictionary.addSlang(autoSlangWord, line);
                    autoGeneratedCount++;
                    System.err.println("⚠️  Error at line " + lineCount + ", auto-generated: [" + autoSlangWord + "]");
                }
            }

            System.out.println("=== LOADING SUMMARY ===");
            System.out.println("✅ Successfully processed: " + successCount + " entries");
            System.out.println("🔧 Auto-generated: " + autoGeneratedCount + " entries");
            System.out.println("📊 Total slang words in dictionary: " + dictionary.getSize());

        } catch (NoSuchFileException e) {
            System.err.println("❌ File not found: " + filePath);
            throw e;
        } catch (IOException e) {
            System.err.println("❌ Error reading file: " + filePath);
            throw e;
        }

        return dictionary;
    }

    // Tạo slang word từ definition (có thể tùy chỉnh logic)
    private String generateSlangWordFromDefinition(String definition) {
        // Mặc định: empty string
        return "";
    }
}


